### PR TITLE
Updated Patterns

### PR DESCRIPTION
**Pull request by blacksunrise56**
Typing `end` will now automatically reduce line indentation.

### CODE REVIEW

**Comment by alefragnani** [comment]
Hi @blacksunrise56 , first of all, thanks for your PR 👍 . 

You could also remove the `procedure` keyword, as reported in https://github.com/alefragnani/atom-language-pascal/issues/17, and also add `protected\\s*$|`.

I didn't understand the addition of `class\const`, because it seems not work (maybe the regex is wrong?), and the `object` (is it FreePascal)? Also, the `decreaseIndentPattern` didn't seems to work fine, because it is _always_ decreasing, no matter if you type `end` or `endless`. I should remove that.

Thanks again

**Comment by blacksunrise56** [comment]
`class` works in:
``` pascal
TMyClass = class(TMyAncestor)
  // indented now
```
And is fully functional on my side.
For `const`:
``` pascal
const
  something = 10; // indented
```
`object` is a FreePascal type that works like:
``` pascal
MyObject = object
  private
    something: 5;
  public
    somethingPublic:10;
```
On the `end/endless` subject, seems like Atom always looks for these regular expressions, not just at the end of the lines. This way I can't think of any fix for this. I'll remove it form this PR.

**Comment by alefragnani** [comment]
Hi @blacksunrise56 

The `class\const` should be, in fact, `class|const` _(two different tags)_. I think it was only a misstyped `\`.

The `const` is ok. It works just like `var`, `type`, etc... but for `class` and `object` I have some concerns. 

When I declare a `class`, I expect to define the _access level_ (`private, protected, public, published`), so it should not indent. On the other hand, `object` conflicts with a `procedure ... of object` construction, so it indents, but shouldn't. In this case, I think the regex should be something like `(?<!of\s)object`, ignoring it when a `of` is present right before.

What do you think?

**Comment by blacksunrise56** [comment]
I see now! I always typed classes this way:
``` pascal
myclass = class(something)
  private
    something2: sometype;
  public
    somethin3: sometype;
end;
```
So the indentation seemed correct. I'll fix it now.
The regex for the object seems right, we can do nothing about variable-length look-behinds so we can only hope nobody puts more than one space before the `object`.
I'll fix these things now.

**Comment by blacksunrise56** [comment]
Oniguruma doesn't like (?i:) inside look-behinds. Should I add something like `[oO][fF]` or `[of|OF|Of|oF]`? Or would it be over-complicating things?

**Comment by alefragnani** [comment]
Yes, I agree that it would over-complicate things. And as you said, the _only one space_ limitation already exists.

I think that _as is_ is already good enougth 👍

**Pull request merged**
